/*
=========================================================
Project: SQL Business Analysis of a DVD Rental Company
Database: Sakila (PostgreSQL)
Author: David-Cristian Mătaru
Date: August 2026

Description:
This project analyzes the operational and financial
performance of a DVD rental company using SQL.
=========================================================
*/
-- =====================================================
-- 1. Revenue Analysis
-- =====================================================
  -- 1. What is the total revenue generated by the company? 
  -- 2. What is the average payment amount? 
  -- 3. How has revenue evolved over time (monthly analysis)? 

-- 1. 
select sum(amount) as total_revenue
from payment; 

-- 2.
select round(avg(amount),2) as average_payment 
from payment;

-- 3. 
select 
	date_trunc('month', payment_date) as payment_month, 
	round(sum(amount),2) as payment_per_month
from payment 
group by payment_month 
order by payment_month;

-- =====================================================
-- 2. Customer Analysis
-- =====================================================
--   4. Who are the Top 10 customers by total spending? 
--   5. Which customers have made the highest number of rentals? 
--   6. Which customers have spent more than the average customer? 
--   7. What is the average amount spent per customer? 

-- 4. 
select c.customer_id, c.first_name, c.last_name, sum(p.amount) as total_spending 
from customer c
join payment p 
on c.customer_id = p.customer_id 
group by c.customer_id, c.first_name, c.last_name 
order by total_spending desc 
limit 10;

-- 5.
select c.customer_id, c.first_name, c.last_name, count(*) as total_rentals
from customer c 
join rental r 
on c.customer_id = r.customer_id 
group by c.customer_id, c.first_name, c.last_name 
order by total_rentals desc;

-- 6. 
select c.customer_id, c.first_name, c.last_name,
	   sum(p.amount) as total_spending
from customer c
join payment p 
on c.customer_id = p.customer_id 
group by c.customer_id, c.first_name, c.last_name 
having sum(p.amount) > (
	select AVG(total_spending)
    from (
        select customer_id,
               sum(amount) as total_spending
        from payment
        group by customer_id
    ) as customer_totals
)
order by c.customer_id;

-- 7. 
select round(avg(total_spending), 2) as average_customer_spending
from (
    select customer_id,
           sum(amount) as total_spending
    from payment
    group by customer_id
) as customer_totals;

-- =====================================================
-- 3. Movie Analysis
-- =====================================================
--   8. Which movies are rented most frequently? 
--   9. Which movies generate the highest revenue? 
--  10. Which movies have rental prices above the average rental price? 
--  11. Which movies are longer than the average movie length? 

-- 8.
select f.film_id, f.title, count(*) as total_rentals 
from film f 
join inventory i 
on f.film_id = i.film_id 
join rental r 
on i.inventory_id = r.inventory_id 
group by f.film_id, f.title 
order by total_rentals desc;

-- 9.
select f.film_id,
       f.title,
       round(sum(p.amount), 2) as total_revenue
from film f
join inventory i
    on f.film_id = i.film_id
join rental r
    on i.inventory_id = r.inventory_id
join payment p
    on r.rental_id = p.rental_id
group by f.film_id, f.title
order by total_revenue desc;

-- 10.
select title,
       rental_rate
from film
where rental_rate > (
    select avg(rental_rate)
    from film
)
order by rental_rate desc;

-- 11.
select title, length 
from film 
where length > (
	select avg(length) 
	from film
)
order by length desc;

-- =====================================================
-- 4. Category Analysis
-- =====================================================
-- 12. Which movie categories generate the highest revenue? 
-- 13. Which categories have the highest number of rentals? 

-- 12.
select c.name, sum(p.amount) as total_revenue 
from film f 
join film_category fc
on f.film_id = fc.film_id 
join category c 
on fc.category_id = c.category_id
join inventory i 
on f.film_id = i.film_id 
join rental r 
on i.inventory_id = r.inventory_id 
join payment p 
on r.rental_id = p.rental_id 
group by c.name
order by total_revenue desc;

-- 13.
select c.name, count(*) as number_of_rentals 
from film f 
join film_category fc 
on f.film_id = fc.film_id 
join category c 
on fc.category_id = c.category_id 
join inventory i 
on f.film_id = i.film_id 
join rental r 
on i.inventory_id = r.inventory_id
group by c.name 
order by number_of_rentals desc;

-- =====================================================
-- 5. Business Insights
-- =====================================================
-- 14. Classify customers into three spending segments based on their total spending: 
-- Gold (≥ $150), Silver ($100–$149.99), and Bronze (< $100), using CASE WHEN. 
-- 15. Rank customers by total spending using RANK() and DENSE_RANK(). 
-- 16. Calculate the cumulative monthly revenue using a Window Function (SUM() OVER()). 
-- 17. Create a VIP Customers View containing customers whose total spending is above the 
-- overall average. 
-- 18. Use a CTE to identify customers with above-average spending. 
-- 19. Analyze revenue by quarter using date functions (EXTRACT() and DATE_TRUNC()). 
-- 20. Evaluate the execution plan of one complex query using EXPLAIN ANALYZE. 

-- 14.
select c.customer_id,
       c.first_name,
       c.last_name,
       sum(p.amount) as total_spending,
       case
           when sum(p.amount) >= 150 then 'Gold'
           when sum(p.amount) >= 100 then 'Silver'
           else 'Bronze'
       end as customer_segment
from customer c
join payment p
    on c.customer_id = p.customer_id
group by c.customer_id, c.first_name, c.last_name
order by total_spending desc;

-- 15.
select c.customer_id, c.first_name, c.last_name, sum(p.amount) as total_spending,
	   rank() over(
			order by sum(p.amount) desc
	   ) as rank,
	   dense_rank() over(
	   		order by sum(p.amount) desc
	   ) as dense_rank
from customer c 
join payment p 
on c.customer_id = p.customer_id 
group by c.customer_id, c.first_name, c.last_name 
order by total_spending desc;

-- 16.
select payment_month,
       monthly_revenue,
       sum(monthly_revenue) over(
           order by payment_month
       ) as cumulative_revenue
from (
    select date_trunc('month', payment_date) as payment_month,
           sum(amount) as monthly_revenue
    from payment
    group by payment_month
) as monthly_revenue_data
order by payment_month;

-- 17. 
create view VIP_customers as 
	select c.customer_id, c.first_name, c.last_name, sum(p.amount) as total_spending 
	from customer c
	join payment p
	on c.customer_id = p.customer_id 
	group by c.customer_id, c.first_name, c.last_name 
	having sum(p.amount) > (
		select avg(total_spending) 
		from(
			select customer_id, sum(amount) as total_spending
			from payment
			group by customer_id
		) as customer_totals
	);
select * 
from VIP_customers 
order by customer_id;

-- 18. 
with above_average_customers as(
	select c.customer_id, c.first_name, c.last_name,
	   sum(p.amount) as total_spending
	from customer c
	join payment p 
	on c.customer_id = p.customer_id 
	group by c.customer_id, c.first_name, c.last_name 
	having sum(p.amount) > (
		select AVG(total_spending)
    	from (
        	select customer_id,
            sum(amount) as total_spending
        	from payment
        	group by customer_id
    	) as customer_totals
	)
)
select * from above_average_customers
order by customer_id;

-- 19.
select payment_quarter,
       extract(year from payment_quarter) as payment_year,
       extract(quarter from payment_quarter) as quarter,
       quarterly_revenue,
       sum(quarterly_revenue) over(
           order by payment_quarter
       ) as cumulative_revenue
from (
    select date_trunc('quarter', payment_date) as payment_quarter,
           sum(amount) as quarterly_revenue
    from payment
    group by payment_quarter
) as quarterly_revenue_data
order by payment_quarter;

-- 20.
explain analyze
select payment_quarter,
       quarterly_revenue,
       sum(quarterly_revenue) over(
           order by payment_quarter
       ) as cumulative_revenue
from (
    select date_trunc('quarter', payment_date) as payment_quarter,
           sum(amount) as quarterly_revenue
    from payment
    group by payment_quarter
) as quarterly_revenue_data
order by payment_quarter;